services:
  nginx:
    container_name: my_nginx
    depends_on:
      - wordpress
    build: #Builds the image from the Dockerfile
      context: ./requirements/nginx/
      args:
        - DOMAIN_NAME=${DOMAIN_NAME}
    image: nginx #assigns the image name
    ports:
      - 443:443
    restart: unless-stopped #restarts the container in case of crash
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception
    env_file:
      - .env

  mariadb:
    container_name: my_mariadb
    build: #Builds the image from the Dockerfile
      context: requirements/mariadb/
      args:
        - DB_NAME=${DB_NAME}
        - DB_USER=${DB_USER}
        - DB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
        - DB_PASSWORD=${DB_PASSWORD}
    image: mariadb #assigns the image name
    ports:
      - 3306:3306
    restart: unless-stopped #restarts the container in case of crash
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception
    env_file:
      - .env

  wordpress:
    container_name: my_wordpress
    depends_on:
      - mariadb
    build: #Builds the image from the Dockerfile
      context: requirements/wordpress/
      args:
        - WP_TITLE=${WP_TITLE}
        - WP_DB_HOST=${WP_DB_HOST}
        - WP_ADMIN=${WP_ADMIN}
        - WP_ADMIN_PASSWORD=${WP_ADMIN_PASSWORD}
        - WP_ADMIN_EMAIL=${WP_ADMIN_EMAIL}
        - WP_USER=${WP_USER}
        - WP_USER_PASSWORD=${WP_USER_PASSWORD}
        - WP_USER_EMAIL=${WP_USER_EMAIL}
        - DB_NAME=${DB_NAME}
        - DB_USER=${DB_USER}
        - DB_PASSWORD=${DB_PASSWORD}
    image: wordpress #assigns the image name
    ports:
      - 9000:9000
    restart: unless-stopped #restarts the container in case of crash
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception
    env_file:
      - .env

volumes:
  wordpress:
    name: wordpress-volume
    driver: local
    driver_opts:
      type: none
      #device: /Users/urbanojr/Documents/inception-data/wordpress #MacOS
      device: /home/ubazzane/data/wordpress
      o: bind

  mariadb:
    name: mariadb-volume
    driver: local
    driver_opts:
      type: none
      #device: /Users/urbanojr/Documents/inception-data/mariadb #MacOS
      device: /home/ubazzane/data/mariadb
      o: bind

networks:
  inception:
    driver: bridge

#secrets:
#  db_root_password:
#    file: ./secrets/db_root_password
#  db_password:
#    file: ./secrets/db_password
#  db_name:
#    file: ./secrets/db_name
#  wp_admin_password:
#    file: ./secrets/wp_admin_password
#  wp_user_password:
#    file: ./secrets/wp_user_password
